### ISSUE TITLE
moose-core not compiling from "d3fe5e9" commit onwards

### ISSUE THREAD

**Issue by hrani** [BhallaLab/moose-core#393] opened 2020-03-06 12:31 UTC
moose-core from "d3fe5e9" commit on-wards not compiling 

~/moose-core/kinetics/Pool.cpp:207:17: error: call of overloaded ‘isnan(double&)’ is ambiguous
     if(! isnan(v))
                 ^
~/hrani/moose-core/kinetics/Pool.cpp:207:17: note: candidates are:
In file included from /usr/include/features.h:375:0,
                 from /usr/include/math.h:27,
                 from /home/bhalla/hrani/moose-core/kinetics/../basecode/header.h:14,
                 from /home/bhalla/hrani/moose-core/kinetics/Pool.cpp:10:
/usr/include/bits/mathcalls.h:235:1: note: int isnan(double)

This is 
GSL version : 1.15, python3, on  Linux-3.10.0-327.el7.x86_64-x86_64-with-centos-7.2.1511-Core

**Comment by dilawar** [comment] 2020-03-07 13:10
Minimum version of `gsl` required is 1.16. It is strange because `cmake` would not allow you to continue. If it did not show you any warning then it is a bug.

Can you please also include the gcc version? With `epel` repo enabled, it compiles fine on CentOS-7. `CMakeCache.txt` file should include all the information I need.

**Comment by dilawar** [comment] 2020-03-08 14:23
I could reproduce this issue on centos7. The gcc version `4.8.5` which is the default on centos-7 can not be used to compile MOOSE since it does not have full `c++11` support. Please use `gcc >= 4.9.0` or `clang++` on centos-7. I've added a check in configuration check (PR #394)

To get recent GCC, use `devtoolset-5` or higher packages available via software collections repository  (see https://wiki.centos.org/AdditionalResources/Repositories/SCL). On gulgula, bebinca they are installed, you need to enable it after login.

```
$ source /opt/rh/devtoolset-8/enable # add to .bashrc to permenently enable it 
```

**Comment by hrani** [comment] 2020-03-09 10:42
scl enable devtoolset-3 bash (GCC 4.9.2) and then checked
scl enable devtoolset-4 bash (GCc 5.3.1)
 cmake ..
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /opt/rh/devtoolset-3/root/usr/bin/cc
-- Check for working C compiler: /opt/rh/devtoolset-3/root/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-3/root/usr/bin/c++
-- Check for working CXX compiler: /opt/rh/devtoolset-3/root/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_WARNS_STRICT_ALIASING
-- Performing Test COMPILER_WARNS_STRICT_ALIASING - Success
-- Performing Test COMPILER_SUPPORT_UNUSED_BUT_SET_VARIABLE_NO_WARN
-- Performing Test COMPILER_SUPPORT_UNUSED_BUT_SET_VARIABLE_NO_WARN - Success
-- Found PythonInterp: /opt/rh/rh-python36/root/usr/bin/python3 (found suitable version "3.6.3", minimum required is "3.5") 
-- MOOSE Version 3.2.1.dev20200309

Still the same error

**Comment by dilawar** [comment] 2020-03-09 11:40
The PR is still pending. Upi or you need to review and merge it. See the linked commit in the issue.

You can replace isnan by std::isnan and it should compile. 

⁣Get BlueMail for Android ​

**Comment by dilawar** [comment] 2020-03-10 09:48
Closing it since #394 is merged. If the issue is not fixed by this PR, please reopen.

**Closed by dilawar** 2020-03-10 09:48 UTC
