### ISSUE TITLE
KSolve Issue

### ISSUE THREAD

**Issue by DineshDevPandey** [BhallaLab/moose-core#11] opened 2015-08-03 07:21 UTC
Need a simple script to
* Test Ksolve
* Profile Ksolve
* Debug Ksolve

**Comment by DineshDevPandey** [comment] 2015-08-03 10:45
Hi @dilawar Please have a look on this issue .  .

**Comment by dilawar** [comment] 2015-08-05 13:46
Either download the whole file, or clone the repository from the url given below:
https://github.com/BhallaLab/moose-chemical/blob/master/ksolve/test_ksolve.py

Compile MOOSE from `https://github.com/BhallaLab/moose-core` using cmake. You
can find the instruction in `INSTALL.cmake`. After successful building, you need
to setup PYTHONPATH to point to moose module e.g. If you have download
moose-core to your HOME.
    
    $ cd moose_core
    $ pwd    # this shows the path of this directory
    $ mkdir -p _build
    $ cd _build && cmake -DDEBUG=ON ..
    $ make -j4 

Once this is successful, the moose python module `_moose.so` will be in
moose_core/python directory. 

    $ export PYTHONPATH=/home/dilawar/moose-core/python

You can also add this line to your `~/.bashrc` file. After updating your
PYTHONPATH, you should be able to load moose in python.

    $ python -m 'import moose'

Above command should pass without any complain.

**Comment by dilawar** [comment] 2015-08-05 14:08
After this, you should be able to run the ksolve script. This script is quite detailed for various objects are manually assigned to clocks. Further, clock dt are also manually assigned. In current release of MOOSE, this is unnecessary.

    $ python test_ksolve.py

    Total time taken: 0.19384098053 sec for 1.0 sec of simulation
    [INFO] + Plotting for kChan_p 
    [INFO] + Plotting for toPsd0 
    [INFO] + Plotting for KGbar 
    [INFO] + Plotting for dend0Ca 
    [INFO] + Plotting for dendKinase 
    [INFO] + Plotting for head0Ik 
    [INFO] + Plotting for head2Vm 
    [INFO] + Plotting for head0Ca 
    [INFO] + Plotting for kChan 
    [INFO] + Plotting for head2Gbar 
    [INFO] + Plotting for head1Ik 
    [INFO] + Plotting for head2Ca 
    [INFO] + Plotting for head1Gbar 
    [INFO] + Plotting for psd0R 
    [INFO] + Plotting for head2Ik 
    [INFO] + Plotting for head1Ca 
    [INFO] + Plotting for head0Vm 
    [INFO] + Plotting for spine0Ca 
    [INFO] + Plotting for dendVm 
    [INFO] Writing plot to mcs.plot.png 

The run-time will differ on your system. You can also disable the Ksolve by
commenting out `makeSolver` function call. In such a case, you will have faster
run but slighly different results. 

To run this script in `gdb` use the following command 

    $ gdb -ex r --args python test_ksolve.py

This will drop you in debugger. You can break at main and do step by step
executing to see how the code is executing.

**Comment by DineshDevPandey** [comment] 2015-08-06 06:12
@dilawar 
I built the moose-core successfully while running the test_ksolve.py I am getting the following error:

[dinesh@punehpcdl02 MoosE_CorE]$ python test_ksolve.py
python: /home1/dinesh/MoosE_CorE/moose-core/ksolve/Stoich.cpp:760: void Stoich::allocateObjMap(const std::vector<Id>&): Assertion `objMap_.size() >= temp.size()' failed.
Aborted (core dumped)

**Comment by dilawar** [comment] 2015-08-06 06:30
I could not reproduce the error on my system `ubuntu-14.04`. I also don't have
SBML installed. Here is my configuration log.

~~~~
cmake ..
++ Moose will be quiet
++ Build for Relase/ No unit tests.
++ DEBUG: GSL_CONFIG_PREFER_PATH: /bin
DBG GSL_CONFIG /usr/bin/gsl-config
-- Using GSL from /usr
-- 
-- Could NOT find LIBSBML (missing:  LIBSBML_LIBRARY LIBSBML_INCLUDE_DIR) 
++ LIBSBML NOT FOUND.  Disabling SBML support.
-- Found HDF5: /usr/lib/x86_64-linux-gnu/libhdf5_hl.so/usr/lib/x86_64-linux-gnu/libhdf5.so
-- Found HDF5-headers: /usr/include
-- Could NOT find Curses (missing:  CURSES_LIBRARY CURSES_INCLUDE_PATH) 
-- Could NOT find Readline (missing:  Readline_INCLUDE_DIR) 
[DEBUG] STATIC_LIBRARIES : 
++ Building native python extension of MOOSE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dilawars/Work/MOOSE/moose-core/_build

~~~~

1. Do a fresh clean and make.
2. Check if PYTHONPATH is pointing to some other version of MOOSE.
3. Run the script with `python -v` and send me the log.

**Comment by dilawar** [comment] 2015-08-11 09:41
There is no update on this issue. Hence closing it.

**Closed by dilawar** 2015-08-11 09:41 UTC
Labels: help wanted
